### ISSUE TITLE
Missing dependency on the documentation: pyfilterbank

### ISSUE THREAD

**Issue by averdones** [AudioCommons/timbral_models#8]
Maybe I'm missing something, but I had to install `pyfilterbank` before being able to `import timbral_models`. Just wanted to point it out in case the documentation needs to be updated.

By the way, in order to install `pyfilterbank`, I just did:

1. `git clone https://github.com/SiggiGue/pyfilterbank.git` 
2. `cd pyfilterbank`
3. `python setup.py install`

**Comment by AndyP103** [comment]
Thanks for noticing this!

It's due to the PyPI distribution being slightly older than the GitHub distribution, and on GitHub, all references to pyfilterbank have been removed since it was unused. 

I've now updated the PyPI distribution to version 0.2.4 which removes the dependency.

Andy
